version: '2'
services:
  spark-master:
    image: bde2020/spark-master:2.3.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8090:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==<yourmasternode>"

  spark-worker-1:
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8091:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==<yourmasternode>"

  spark-worker-2:
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8092:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==<yourworkernode>"

  spark-worker-3:
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8093:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==<yourworkernode>"